### ISSUE TITLE
Explain the stages of deployment in the railway

### ISSUE THREAD

**Issue by bugbounted** [lucdotdev/youtube_tiktok#1]
Hi [lucdotdev](https://github.com/lucdotdev),
please help me how to deploy this project on railway. I'm fast lookup files & see MONGODB_URI & PORT enviroment variables needed.
My important question is how to make youtube api v3 Oauth & set client_id & project_id in client_secret.json to work fine in serverless docker containers to not answer oath webui token ?
waiting for your response
finest regards

**Comment by bugbounted** [comment]
My failed on runtime app log after deployed on railway is :
`> youtube_tiktok@1.0.0 start /usr/src/app
> node server.js
/usr/src/app/node_modules/twilio/lib/rest/Twilio.js:142
throw new Error('username is required');
^
Error: username is required
at new Twilio (/usr/src/app/node_modules/twilio/lib/rest/Twilio.js:142:11)
at initializer (/usr/src/app/node_modules/twilio/lib/index.js:10:10)
at Object.<anonymous> (/usr/src/app/src/core/utils.js:3:33)
at Module._compile (internal/modules/cjs/loader.js:1256:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
at Module.load (internal/modules/cjs/loader.js:1105:32)
at Function.Module._load (internal/modules/cjs/loader.js:967:14)
at Module.require (internal/modules/cjs/loader.js:1145:19)
at require (internal/modules/cjs/helpers.js:75:18)
at Object.<anonymous> (/usr/src/app/tikitoku.js:5:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube_tiktok@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube_tiktok@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-19T10_39_29_734Z-debug.log
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start`
